name: DB-Fahrplan-Bot

on:
  workflow_dispatch: # Erlaubt das manuelle Starten per Button
  schedule:
    - cron: '*/15 * * * *' # Startet automatisch alle 15 Minuten

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    permissions: # Stellt sicher, dass der Bot Schreibrechte hat
      contents: write

    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: Python installieren
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Bibliotheken installieren
        run: pip install requests

      - name: Script ausfueren
        run: python fetch_data.py

      - name: Daten speichern und hochladen
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daten.json
          # Commit nur ausfuehren, wenn sich die Daten geaendert haben
          git commit -m "Echtzeit-Update Zerbst" || echo "Keine Aenderungen gefunden"
          # Push mit Token-Authentifizierung
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git main
