name: DB-Fahrplan-Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *' # Aktualisiert alle 15 Minuten automatisch

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: Python installieren
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Bibliotheken installieren
        run: pip install requests

      - name: Script ausfuehren
        env:
          DB_CLIENT_ID: ${{ secrets.DB_CLIENT_ID }}
          DB_CLIENT_SECRET: ${{ secrets.DB_CLIENT_SECRET }}
        run: python fetch_data.py

      - name: Daten speichern und hochladen
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daten.json
          git commit -m "Zerbst Update mit offizieller API" || echo "Keine Ã„nderungen"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git main
          
