name: DB-Fahrplan-Bot
on:
  workflow_dispatch:
jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install requests
      - run: python fetch_data.py
      - name: Commit data
        run: |
          git config user.name "Bot"
          git config user.email "bot@github.com"
          git add daten.json
          git commit -m "Echtzeit-Update" || exit 0
          git push
          
